### ISSUE TITLE
Having trouble setting up.

### ISSUE THREAD

**Issue by Podginator** [pgaskin/NickelHook#6]
Hi, 

I have been struggling with this for a few days now - and I'm sure it's something trivial I am doing wrong, but I am frustrated.

I am having difficulties setting things up. I can correctly combine, and I can correctly edit the preload to get the library to load. 

When I do I get the following error: 

`fatal: dlopen libnickel: libQtSolutions_IOCompressor-2.3.so.1: cannot open shared object file: No such file or directory`

I can get past this by opening the files it throws for before the lib nickel is opened. 

```
dlopen("/usr/local/Kobo/libQtSolutions_IOCompressor-2.3.so.1", RTLD_LAZY|RTLD_NODELETE);
dlopen("/usr/local/Kobo/libsunpinyin.so.3", RTLD_LAZY|RTLD_NODELETE);
dlopen("/usr/local/Kobo/librmsdk.so.1", RTLD_LAZY|RTLD_NODELETE);
```

It seems to then load, it informs me that the symbol has been replaced. 

However, it seems to just keep loading itself over and over.  

All I am currently doing is printing, and then returning the original implementation. Absolutely nothing is printed. I originally thought this might be a null or something similar, but I'd expect it to log before this happens. 

https://gist.github.com/Podginator/8bb19abf009673abc8eb1cf9f19afe05

I am probably doing something wrong, but I have had similar issues trying to load the examples in kobo_mods, and NickelClock. 

Any help is greatly appreciated.

**Comment by pgaskin** [comment]
You shouldn't need to add it to preload; NickelHook mods just need to be put in `/usr/local/Kobo/imageformats`.

If you're starting Nickel manually, ensure you're setting the env variables (e.g., `LD_LIBRARY_PATH`) set by the default init scripts.

**Comment by Podginator** [comment]
Thank you - I went down an incorrect rabbit hole, but just putting it in /usr/local/Kobo/imageformats worked fine.
